### ISSUE TITLE
DeviceInfo.getMacAddress() returns diffrent string every time

### ISSUE THREAD

**Issue by Rob2k9** [react-native-device-info/react-native-device-info#1100]
Hi there i installed this modual on a fresh android app just a few days ago i am using react-native 0.63 on android 7 

when i grab the device mac address its returning a diffrent mac address everytime the app is opened sometimes it even returns random strings 

using this modual on the same xaomi t8 pro i have been given the following strings as mac addresses 

 f7dfc12f8e9a34f5 
 0C:EE:99:3C:72:C7
 56f1c5605c75ebab
 10b914b5feb58594
 02:00:00:44:55:66

this is just from opening and closing the application this is the code i am using 

    GET_MAC = async () => {
        DeviceInfo.getMacAddress().then(mac => { this.setState({ Devicemac: mac }); });
    }

**Comment by mikehardy** [comment]
returning real mac addresses is handing apps a hardware identifier and systems don't do hand out hardware identifiers anymore, they all have strategies to either deny access or randomize it so information doesn't leak and provide actually unique hardware identifiers

So I'd say this is expected behavior, I wouldn't rely on the mac address for anything. You can inspect the code here and see we call the API correctly, but it can return whatever the vendor wants it too - that's out of our control
