### ISSUE TITLE
Need Device Token

### ISSUE THREAD

**Issue by avadheww** [react-native-device-info/react-native-device-info#1104]
Hello,
I need the device token while register or login the user. 
Will I get that with the help of this package?

If not then is there any way to get the device token? i am not implementing the push notification in my App but i need to store the device token.

**Comment by mikehardy** [comment]
This might be what you want https://github.com/react-native-device-info/react-native-device-info#getinstanceid

But in all seriousness - if you are interested in tokens and device ids etc these things are *very* specific to use cases and platforms. In order to be successfully in your implementation you will need to be familiar enough with everything that I could ask the question and you answer it for me, as opposed to me answering you. There's no other way - read the docs, read the code, learn under what conditions they are invalidated (or should be invalidated!) etc etc
