### ISSUE TITLE
getHms does't work correctly

### ISSUE THREAD

**Issue by m1kys** [react-native-device-info/react-native-device-info#1160]
## Summary

| Device | Huawei |
| Model | GLK-AL00 |
| Version     |  8.0.0  |
| Affected OS | Android |
| OS Version  | 10 |

## Current behavior

**getHms** on Huawei device returned false
**getGms** on Huawei device returned false (because my device doesn't have google services)

## Expected behavior

**getHms** on Huawei device returned true

**Comment by mikehardy** [comment]
This could be as a result of #1156

Specifically this line looks suspect https://github.com/react-native-device-info/react-native-device-info/pull/1156/files#diff-0b8fd946e3e94d3937d6257dd1f4717baffa0fa698af59c56dbd1040380c0994R526

It is possible for you to reach right in to node_modules and try reverting that one line, if you could do that and test HMS and GMS device it would be a great service and I could release a patch today, but I have no HMS device to test.

**Comment by GhadaAb** [comment]
I have a huawei device (without google services) but always DeviceInfo.hasHms return false

**Comment by mikehardy** [comment]
@GhadaAb you could advance the conversation by following the direction in my comment: https://github.com/react-native-device-info/react-native-device-info/issues/1160#issuecomment-758623278

**Comment by NicoleCH35** [comment]
@mikehardy The line you mentioned that looks suspect seems to be the issue. 

I was having the same issue where hasHMS would return false no matter what. 

I then imported com.google.android.gms.common.ConnectionResult.
Updated both the **hasHmsSync** and **hasGmsSync** functions to use **ConnectionResult.SUCCESS** instead of 0.

I've tested on a HMS device and a GMS device. Both seem to work as expected.
