### ISSUE TITLE
Duplicate case value 'UIUserInterfaceIdiomPad

### ISSUE THREAD

**Issue by tungtrana3** [react-native-device-info/react-native-device-info#1161]
react-native-device-info : "^7.3.1",
 Xcode Version 11.5 (11E608c)
React-Naitve version 0.63.3
iOS 13.0

## Current behavior
When I build my app on Xcode, I receiver error "Duplicate case value 'UIUserInterfaceIdiomPad' " at RNDeviceInfor.m line 116.
But it ok if I delete "case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;" at this line.

<img width="746" alt="Screen Shot 2021-01-14 at 15 39 36" src="https://user-images.githubusercontent.com/52845932/104565328-b788dc80-567e-11eb-8800-70b8261b5f60.png">

## Expected behavior

I don't want to do this every time I install the project. How do I fix it?

Thanks and best regards

**Comment by mikehardy** [comment]
Check release notes and changelog and search issues list prior to logging issues please
Granted, this one was a gotcha. That version (and 8.x) require up to date Xcode i.e. 12
If you develop for ios the general expectation is that you update your Xcode when they release it in order to support modern iOS versions
If you don't do that you are basically at your own risk, though I did not intend to break people on purpose.
For Xcode 11 if you must stay on it for whatever reason, pin your version here to a prior version

**Comment by HoangNgocThang** [comment]
Duplicate case value 'UIUserInterfaceIdiomPad'
reactnative: 0.63.4
xcode:11.5

**Comment by mikehardy** [comment]
@HoangNgocThang update your Xcode, or use older react-native-device-info - the comments above cover it so you can move forward
