### ISSUE TITLE
What will getUniqueId() return with the upcoming iOS 14.5 changes?

### ISSUE THREAD

**Issue by floelm** [react-native-device-info/react-native-device-info#1224]
Hello,

I was curious if someone knows that will be returned by `getUniqueId()` with the iOS update tomorrow. For example what happens if a user first gives no tracking permission (package will generate random UID and save it in Keychain and NSUserDefaults) and then gives permission afterwards. Will `getUniqueId()`  return the generated UID or the actual device id for tracking?

**Comment by mikehardy** [comment]
No idea - but I suppose you could reach in to the source and simulator the behavior. I haven't looked at that code in forever so I'm not sure exactly how the precedence of ID source works. If it's working correctly (in my mind), regardless of the initial source it should return the same thing after first call on the same installation of the app on the same device, if not I think that's a bug.

The important part is not what the source is (IMHO) but that it's the same for the same installation.

Worth exploring is whether we are (or would be) violating the spirit of the tracking rule by having any unique id for an install at all if the user hasn't granted permission

**Comment by ttkien** [comment]
I am curious about is getUniqueId() `Such as the device's advertising identifier, or other device-level ID` or App-level ID?

**Comment by mikehardy** [comment]
Looks like you found your answer @ttkien

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info/blob/dc9caef58840684c770690f5a9f945d098eb76c0/ios/RNDeviceInfo/DeviceUID.m#L159-L165

We do use IDFV not IDFA, which means you are likely not *forced* to ask https://developer.apple.com/app-store/user-privacy-and-data-use/ however it is a gray area and though you are not *forced* to ask it is likely that you fall into one or more of the categories on the link I just posted.

I'm guessing IDFV will return no matter what since it is single vendor not cross-vender. Closing this unless someone has direct experience otherwise (at which point we may reopen if necessary)

**Comment by MayoudP** [comment]
Thanks for the research ! Appreciated 🙏
