### ISSUE TITLE
Invalid Mac Address in Android 11

### ISSUE THREAD

**Issue by niljaisw** [react-native-device-info/react-native-device-info#1248]
## Summary

The getMacAddress mrthod is returning invalid mac address on Android 11. 

|             |     |
| ----------- | --- |
| Version     | 8.1.3   |
| Affected OS | Android 11   |
| OS Version  | Android 11   |

## Current behavior

getMacAddress method returns invalid mac address. 

## Expected behavior

Should return the random mac address of connected SSID.

**Comment by mikehardy** [comment]
I don't believe that's going to happen
https://developer.android.com/about/versions/10/privacy/changes#randomized-mac-addresses

**Comment by mikehardy** [comment]
A question @niljaisw - when you say "invalid" do you mean "does not conform to MAC addressing / formatting standards" or do you mean "I did not get actual hardware MAC address and I wanted it?"

That's really important when it comes to determining how / whether to handle this

**Comment by niljaisw** [comment]
@mikehardy, by invalid mac address i meant I did not get the mac address, random or actual device mac address. I checkout the link you have mentioned and did some research my self,  it seems like Android have disabled both [direct API](https://developer.android.com/reference/android/net/wifi/WifiConfiguration#getRandomizedMacAddress()) to get the mac address and the [hardware address](https://developer.android.com/training/articles/user-data-ids#mac-11-plus) hack. 

The IP address based approach seems interesting, i have not yet tested it.

**Comment by mikehardy** [comment]
@rohitshampur-dev I just read the privacy documents again, and the two links here, and I'd like to focus discussion here prior to moving on to any PR.

While I am strongly for exposing all device information possible via this module, I am not for working around privacy related concealment of device identifiers, in general.

What that means here concretely is: if Android is limiting access to the MAC address, and in general you cannot get it, then I do not want to try to work around that, I do not believe concealing this platform restriction benefits anyone in the end.

My criteria for that decision is that if we attempt to construct some sort of not-really-correct MAC address we are in essence making an abstraction - a new MAC address API that sits on top of the MAC address that goes out on the network in other cases, and it will be different than what other devices on the network actually see. That is what is called a "leaky abstraction" and it causes subtle problems because programmers get one idea in their head of how a system behaves (our abstraction) but then later in certain cases they have to remember all the complexity anyway (that the MAC is actually randomized and different and not really available we were just faking it (that's what happens when an abstraction is "leaky")

Unless there is a way to get the real MAC address - and I do not think there is - I don't see value in working around the system here.

I think there is more value in simply leaving a reference to the google privacy changes document in our API documentation, with the statement that you will get an empty string (or whatever you get, determined via testing) on Android >= 10

**Comment by niljaisw** [comment]
@mikehardy Reasonable! If anyone has hard dependancy on Mac Address can use the ipv6 approach.
