### ISSUE TITLE
Application uses trackable deviceidentifiers

### ISSUE THREAD

**Issue by Nidhinkmadhu** [react-native-device-info/react-native-device-info#1261]
## Summary

|             |     |
| ----------- | --- |
| Version     | 5.5.8  |
| Affected OS |Android   |
| OS Version  | 10   |

## Current behavior

While checking the fortify scan report it is showing this error "The application was found to access identifiers that can be used to track a specific device across applications and potentially across device factory resets .Use of these identifiers may cause privacy concerns and/or be regulated in certain jurisdictions .The application was found to have that accesses Android ID which can be used to track specific device .

issue is found in file : com/learnium/RNDeviceInfo/RNDeviceModule.java
 

## Expected behavior

No warning should come up

**Comment by mikehardy** [comment]
I'm sorry, this issue is absurd.
Of course it provides access to trackable identifiers, it provides access to every bit of information possible about a device.
Be a responsible developer and treat your users with respect is the answer I think?

You don't even specify which identifier!

Not actionable -> closing

**Comment by slvtrs** [comment]
@mikehardy haha if it didn't access any of those identifiers there'd undoubtably be issues open for each one that was missing.

I understand the package must be able to access these identifiers, but could you confirm that the package itself never transfers any of this data off the device?

I think that's where the privacy concern comes from and I was unable to find any policy info in the readme or repo that addresses this.

**Comment by mikehardy** [comment]
I can understand privacy-oriented people wanting to know more however: There is no policy info needed: These are APIs, nothing more.

An analogy: you walk into a fabricator of large concrete pipes and ask them about what they do with all the contents of the pipes, because you are concerned about sewage spills.

I'm also concerned about sewage spills (and privacy), I get it.

Well, in our analogy, we make the pipes (our API calls) as best we can so they function as specified, but what you do with them? Not under our control. There is no flow here.

So I guess if there is a policy statement to be made: this module will never actually do a thing with any piece of data unless specifically requested, at which point it's up to the app consuming the module

Even better, it's open source. Inspect and confirm.
