### ISSUE TITLE
Feature request: Get disk storage used by app?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-device-info/react-native-device-info#1266]
Is it possible to implement a method to get the total disk space used by the app? Is it even possible on the native side? I'm willing to send a PR if this is feasible.

**Comment by mikehardy** [comment]
Hmm the system certainly displays the same in system settings doesn't it? This would be useful.
I admit I am not sure exactly what system APIs are provided off the top of my head, but I'm certain you can get the root of your various available folders and enumerate entries / total them. So it's certainly possible both with File APIs and maybe a system `du` call

 A quick search on stackoverflow got a bunch of hits on memory usage (we've already got that...) but nothing on disk. So I guess you'd have to enumerate the available storage roots for the app, de-duplicate them in case they were just links pointing to the same spot (like, no external storage? not sure if this is even a real edge case or just something to check to make sure they are really unique in practice then ignore) then do a standard recursive directory/file-enumeration sum

**Comment by cristianoccazinsp** [comment]
Hmmm, so enumerating all folders and files is the only way? It's a shame that there's not a less resource-intensive option.

**Comment by mikehardy** [comment]
Unless the system is maintaining a count in sync with disk state, I think even the system interface must do the same. I notice most of those spin/update dynamically when examined. Which is to say, I think the computation time is the same regardless, I think the more important thought is: I wish there was a less code-intensive option :smile:

**Comment by cristianoccazinsp** [comment]
You are right, it may be way too much code for little benefit.  Our goal was to find out why the device's storage is low (is it our app, or a general issue), but I guess the effort is not really worth it.  You would be amazed how many users are there running with < 500mb of storage...

**Comment by mikehardy** [comment]
I live in Ecuador, where it is totally common to a) have used all your prepaid data 2) have effectively zero internal storage so you are constantly uninstalling and reinstalling apps because all the apps you need do not actually fit in internal storage and then 3) have the microsd card handed down to you flake out or something and lose everything while 4) your phone screen is totally cracked and it's not worth fixing

Nothing surprises me anymore! But it has all made me very sensitive to user constraints. During the pandemic, everyone brought out whatever crap handset they had laying around and shared them with who ever needed them just to access online education platforms, or they didn't even get a chance to learn. Quite the perspective shift seeing it happen in real time, for a dude (me) from the US in the Bay Area originally where it basically rains flagship handsets in a monsoon
