### ISSUE TITLE
Expose hasGms / hasHms flow type support

### ISSUE THREAD

**Issue by conradchenghk01** [react-native-device-info/react-native-device-info#1270]
Hi support,

is it okay to expose flow type support for hasGms and hasHms props in index.js.flow file?

We facing a flow issue when our app start flow checking

hasGms: () => Promise<boolean>
hasHms: () => Promise<boolean>

**Comment by mikehardy** [comment]
Hello! I'd much prefer that the flow types are migrated to https://github.com/flow-typed/flow-typed actually - the library is now built in typescript and the flow types are no longer actively checked or maintained for correctness (as you've found) since none of the current maintainers nor most of the users have an interest in flow typing. If you could propose a PR to flow-typed to do the same so they'd see more attention+care that would be a better path forward I think
