### ISSUE TITLE
Property 'isiosapponmac' not found on object of type 'nsprocessinfo *'

### ISSUE THREAD

**Issue by ripplezen** [react-native-device-info/react-native-device-info#1271]
Property 'isiosapponmac' not found on object of type 'nsprocessinfo *'

I am getting this error on Xcode build and I'm sure there is a simple way to fix it. Any ideas? If you comment out the line the project builds and functions normally on IOS devices. I am at IOS 10.0 minimum requirement.

Error info:
RNDeviceInfo.m line 120.

**Comment by mikehardy** [comment]
Interesting - the important part here will be Xcode version I think, as new versions of Xcode are the things that bring in new symbols for compile to work, whether you are targeting new iOS versions or not.

https://developer.apple.com/documentation/foundation/nsprocessinfo/3608556-iosapponmac

The symbols was added for iOS14+ indicating that Xcode 12+ will be required for successful compilation per https://xcodereleases.com/

I believe requiring Xcode 12 is fairly reasonable and you should be able to update for free. I understand some users have difficulty updating to Xcode 12.5 (because it requires Big Sur and some people are stuck on Catalina) but this is different, Xcode 12 has been out for nearly a year?

I'm going to close this as I believe that's the solution, and as mentioned you can comment it out if you like (or simply return false or similar) via https://github.com/ds300/patch-package if truly needed in your specific project context
