### ISSUE TITLE
Is it possible to find if end user uses mock location apps?

### ISSUE THREAD

**Issue by Yandamuri** [react-native-device-info/react-native-device-info#1282]

**Comment by mikehardy** [comment]
If you don't see it in the API, then it is not possible with this module, no. And I don't see that in the API.

For modern android, you should work with whatever location package you are using and access the mock property on the location objects you receive https://stackoverflow.com/a/34726023/9910298

For iOS, I'm not sure it's possible https://stackoverflow.com/questions/29232427/ios-detect-mock-locations

In all cases a realistic enough simulation will be very difficult to detect, but will probably also require rooting/jailbreaking, which you could detect via DeviceCheck and/or AppAttest on iOS or SafetyNet on Android, but that's not a feature here unless you want to contribute it. There are packages for each of those specific items, plus I know react-native-firebase has "AppCheck" which does DeviceCheck and/or SafetyNet verification (I know this since I just implemented it there... https://github.com/invertase/react-native-firebase/pull/5581 )
