### ISSUE TITLE
Getting a different ID with getUniqueId() on Android in debug mode and release mode

### ISSUE THREAD

**Issue by ChethanAndroid** [react-native-device-info/react-native-device-info#1318]
Getting a different ID with getUniqueId() on Android in debug mode and release mode

debug mode :  'Unique ID', ':', '0bb6d96aef12fcc3'
release mode:  'Unique ID', ':', '2d94525cc9f2dbe4'

|             |     |
| ----------- | --- |
| Version     | 8.3.3  |
| Affected OS | android & ios   |
| OS Version  | Latest   |

## Current behavior

Getting a different ID with getUniqueId() on Android in debug mode and release mode

debug mode :  'Unique ID', ':', '0bb6d96aef12fcc3'
release mode:  'Unique ID', ':', '2d94525cc9f2dbe4'
Play store build : 'Unique ID', b0901718730e08a6

## Expected behavior

device info ID should be unique in all the releases.

**Comment by mikehardy** [comment]
This is tempting to troubleshoot since it seems obvious they should be the same.
But, how are you switching modes? If you uninstall, then this is expected behavior. If you just install release mode over debug, this is unexpected.

So I don't have all the steps needed to spend time on it, with more details someone could perhaps help

**Comment by ChethanAndroid** [comment]
Play store build 
'Unique ID', b0901718730e08a6

In every build getting a new ID then, we are not getting a unique id from the device.
Any suggestion on this.

**Comment by mikehardy** [comment]
You did not answer my question, and I required it to progress so I have nothing to add, sorry.

**Comment by ChethanAndroid** [comment]
Sorry, we are uninstall and installing the app all the time 
For different mode of build  to install.

**Comment by mikehardy** [comment]
If you uninstall and reinstall instead of just installing over the current installation, I believe you *must* expect the ID to change.
That is expected behavior. The ID is not persistent across uninstall/reinstall. It is persistent over new versions only for Android.

Google and Android is *specifically* against the idea that identifiers persist. The whole goal of mobile ecosystems over the last few years has been obviously against the idea that users are tracked without their knowledge, or tracked at all. So, no persistent identifiers are exposed are allowed anymore really.

As a user, I have to admit, I like this. As a developer, we simply must adapt.

**Comment by ydv0121** [comment]
@ChethanAndroid i am getting same output like you.
