### ISSUE TITLE
iPhone 13 is not getting considered as notch device

### ISSUE THREAD

**Issue by upbind** [react-native-device-info/react-native-device-info#1319]
I am using 2 conditions to check for notch device and iPhone Notch Device.

export const isIphonex = Platform.OS === 'ios' && DeviceInfo.hasNotch()
export const notchDevice = DeviceInfo.hasNotch();

But it seems these conditions are somehow not working for Iphone 13 IOS 15.
Is there anything i am missing.

Device - Iphone 13 Pro
IOS - 15

**Comment by mikehardy** [comment]
Without version information I can't say whether you have the right notch list or not.
However I have to say in practice using "hasNotch" is not a great idea anyway since - okay - it has a notch but is it in the center? Or a pinhole on the side? How big is it? Are the corners curved, and if so how much?

It's just not really useful information. What you really want is device insets and what you want with *those* is to know the safe area you can actually use.

Which is all to say, with current versions of this library the iPhone 13s should be in the list (check the PR list and the code, you'll see) but what you really want is 

https://github.com/th3rdwave/react-native-safe-area-context

Possibly with a "CustomStatusBar" component inside the SafeAreaProvider in order to have the status bar match your app theme and handle the insets welll

```typescript

const CustomStatusBar = () => {
  const insets = useSafeAreaInsets();
  return (
    <View style={{backgroundColor: colors.blue.color, height: insets.top}}>
      <StatusBar
        backgroundColor={colors.blue.color}
        animated={true}
        barStyle="light-content"
      />
    </View>
  );
```

All of that will be a much better result then knowing you have a notch or not, in my opinion
