### ISSUE TITLE
Empty MAC address

### ISSUE THREAD

**Issue by quentingirard** [react-native-device-info/react-native-device-info#1340]
## Summary

|             |     |
| ----------- | --- |
| Version     |8.1.2   |
| Affected OS | Android   |
| OS Version  | 11   |
| React-native | 0.64.1 |

## Current behavior
After upgrading Google API from 29 to 30 and method getMacAddress() return an empty string.

You can try to reproduce with this repo: https://github.com/Wavemind/liwi-medal-reader
branch **feature/upgrade-google-api**
A console.log is displaying result of getMacAddress()

## Expected behavior
Should return current MAC address

**Comment by mikehardy** [comment]
Hi there - please search then log https://github.com/react-native-device-info/react-native-device-info/issues?q=is%3Aissue+mac
Previous issue has a comment that is a minimal reproducible example (that is, our example app here) and it works https://github.com/react-native-device-info/react-native-device-info/issues/1323#issuecomment-936640005

I will not use a larger app to diagnose, our sample app is how we pinpoint issues and verify functionality. If you can tweak the sample app to somehow not respond to APIs well (maybe it does not, now?) then we can reopen that issue 1323 and work through it there. 

Otherwise the difference will be somewhere between what the sample is (minimal) and your repro or device-specific
