### ISSUE TITLE
getPhoneNumber stopped working in Android 12

### ISSUE THREAD

**Issue by colbygarland** [react-native-device-info/react-native-device-info#1364]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.8   |
| Affected OS | Android   |
| OS Version  | 12   |

## Current behavior

`getPhoneNumber` was pulling the device's phone number reliably for Android 10 and 11. Since the update to 12, none of my test devices (Pixel 3A and android emulator from Android Studio) have been pulling the phone number anymore.

## Expected behavior

`getPhoneNumber` should correctly pull the device's phone number from the device.

**Comment by mikehardy** [comment]
Hi there, strange - I don't see anything in the privacy changes for 12 that would do that.
There was this for 11, you may need a different permission request https://developer.android.com/about/versions/11/privacy/permissions

This is corroborated, somewhat, by our out of date example which is still targeting 10 (API 29) and runs just fine with phone number showing on Android 12 emulator.

Please verify your permissions request I think?

Otherwise:
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

...or dig into the relevant java code in node modules and add some `System.err.println("Here I am etc etc");` to figure out what's happening in the control flow - the method's pretty basic, should be easy to catch.

**Comment by colbygarland** [comment]
I did some looking, turns out I needed to add `<uses-permission android:name="android.permission.READ_SMS" />` permission to my manifest, as well as change the permissions request to `PermissionsAndroid.PERMISSIONS.READ_SMS` instead of `PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE`. 

Interestingly enough, the `READ_PHONE_NUMBERS` permission didn't work, it was the `READ_SMS` that worked for me. Confirmed this works on the emulator, and a physical Pixel 3A, both running Android 12.

Closing this as this solves my problem, thanks for looking into this for me @mikehardy ! Appreciate it.
