### ISSUE TITLE
Add location providers event listener

### ISSUE THREAD

**Issue by CptFabulouso** [react-native-device-info/react-native-device-info#1368]
## Description

Hi,  I'd like to have event listener to listen to changes to location providers, such as user turning their location service on and off, basically what is currently provided by `getAvailableLocationProviders` and `isLocationEnabled`. I could not find any lib implementing this (even thought it's hard to find because almost everywhere it's about permission, not the module itself)

## Use Case

I watch user's location (using https://github.com/Agontuk/react-native-geolocation-service), but if he turns the location service off, the listener fails and I'd like to restart it when user turns the location service on again.

**Comment by mikehardy** [comment]
Hi there - I think this properly belongs in the actual GPS modules, since they already implement a listener.
Specifically, it should go here https://github.com/Agontuk/react-native-geolocation-service/blob/master/android/src/main/java/com/agontuk/RNFusedLocation/LocationChangeListener.java - overriding the onProviderXYZ methods

I don't believe there is any place to reliably get this information that is not inside what I think of as the "location permissions" barrier, and that's not a place we want to go with device info. We will get information where possible + easy, but for detailed use cases, detailed modules like the one you are using should get the extra complexity
