### ISSUE TITLE
iPhone 13 Pro Max model / hasNotch not working

### ISSUE THREAD

**Issue by wkibbler** [react-native-device-info/react-native-device-info#1370]
## Current Behaviour
using iPhone 13 Pro Max the `hasNotch` method returns `false`
I believe this is caused by the fact the `getModel` method returns `iPhone` instead of `iPhone 13 Pro Max` as it does with other models.

## Expected behaviour
`getModel` should return full name of the model, `hasNotch` should return true for the `iPhone 13 Pro Max`

**Comment by mikehardy** [comment]
Hi @wkibbler - if you post a PR to fix the same, we can merge and release it pretty quickly

**Comment by roryf** [comment]
Looks like this was fixed in #1309

**Comment by mikehardy** [comment]
Nice @roryf - @wkibbler you did not specify your version. Maybe you're just out of date? Otherwise perhaps there's a new product code out there that needs a PR to handle.

**Comment by YitzhakHefetz770** [comment]
Same issue (iPhone 12 - iOS 15.0).
HasNotch does not seem to work on iOS 15.x
Always returns false

**Comment by mikehardy** [comment]
@YitzhakHefetz770 what's reported by the native APIs with regard to module number? Perhaps it's just not matching correctly. If you want it to work you'll need to investigate deeply to see what exactly is going on, why it's not working, and post a PR

**Comment by schie** [comment]
Hi @wkibbler and @YitzhakHefetz770,


While I don't have a physical iPhone 13 Pro Max, the example application on a simulator on iOS 15.2 says it does have a notch.

![Screen Shot 2022-02-25 at 11 36 42 PM](https://user-images.githubusercontent.com/4561856/155829200-b736e413-402a-4891-865d-2a92632164de.png)


iPhone 13x has been supported in `hasNotch` since [v8.3.2](https://github.com/react-native-device-info/react-native-device-info/releases/tag/v8.3.2)

Please make sure version of react-native-device-info is up-to-date.

**Comment by schie** [comment]
Once upgraded, please let us know if it's still not working for you. 

If it is working, please close.

**Comment by MatteoGauthier** [comment]
Don't work on iphone 13 pro with ios15.2 (simulator) and react-native-device-info 8.5.0

**Comment by schie** [comment]
@MatteoGauthier 

Did you run pod install?
