### ISSUE TITLE
Built in-mock for getUniqueId does not work in Jest test - versions 8.3.0 and 8.4.9

### ISSUE THREAD

**Issue by princefishthrower** [react-native-device-info/react-native-device-info#1383]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.30, 8.4.9   |
| Affected OS | N/A   |
| OS Version  | N/A  |

## Current behavior

Calling `getUniqueId()` doesn't return anything when being called in a Jest test.

## Expected behavior

I should get a mocked string of device ID. (or at least an empty string would be good enough!)

Anybody seen this occur? yes, I have followed the docs and added the following code to my `jest.setup.js` file:

```
import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock';

jest.mock('react-native-device-info', () => mockRNDeviceInfo);
```

(and yes, I AM using that setup file)

I originally had 8.3.0 in my project, so I thought upgrading to the latest, 8.4.9 couldn't hurt.  It appears however this issue occurs in both of those versions.

**Comment by mikehardy** [comment]
Strange

Here's the mock definition:
https://github.com/react-native-device-info/react-native-device-info/blob/d9b8cb5af3c166a914b48fdaa22df0a7dcb8397f/jest/react-native-device-info-mock.js#L133

Here's the method it refers to:
https://github.com/react-native-device-info/react-native-device-info/blob/d9b8cb5af3c166a914b48fdaa22df0a7dcb8397f/jest/react-native-device-info-mock.js#L6

So you should be getting string 'unknown'

I can't understand why it wouldn't. I'm afraid you'll have to dig more and find the root cause, it may be project specific as jest setups may vary wildly, and no one else has reported this

**Comment by princefishthrower** [comment]
I can't explain it either. As it turns out, in our codebase, we had a wrapper around `getUniqueId` we call `getDeviceUniqueId`, so I ended up mocking _that_ function as a work around (and returning a real android device ID didn't hurt for our tests):

```
jest.mock('./src/helpers/utils', () => {
  const originalModule = jest.requireActual('./src/helpers/utils');
  return {
    __esModule: true,
    ...originalModule,
    getDeviceUniqueId: () => 'a4a9e07a10f49083',
  };
});
```

I've got a whole mess of TypeScript integration with Gherkin specifications and cucumber.js, and I've also got a massive jest.setup.js with various mocks, so it could be any one of those or a combination of those things.
