### ISSUE TITLE
Huawei Mobile Services SDK not compliant with Google Play Policies 

### ISSUE THREAD

**Issue by thanhcuong1990** [react-native-device-info/react-native-device-info#1392]
## Summary

Google Play Support just sent me an email Today about issue with Huawei Mobile Services SDK. 
I was try to search which packages has used Huawei by `grep -R huawei node_modules`. But only `react-native-device-info` has used it. 

Can you guys help to take a look?

<img width="756" alt="Screen Shot 2022-03-17 at 11 11 50 am" src="https://user-images.githubusercontent.com/3401929/158735848-d9350d54-8d7b-41ff-873e-bad2fab625fe.png">

## Issue 
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.

After 120 days, new app releases containing this non-compliant version of this SDK will be rejected. This SDK version violates [Device & Network Abuse](https://notifications.google.com/g/p/AD-FnEw_GSHL5QHyyHMXukKeYiEuN1DNdbXfWjgSVauPSSpraJjHTtb-VH7coWJoh5REavyesf19kRiPCq9BRf1-T79bpCzk3MoMN9uwM8MG_2K3dxAYSiwzp718VrOfrHWIzhqoxqOWMn6tXg) policy.

Given the nature of the SDK, we request that you remove it from the version of your app submitted to the Play Store.

**Comment by mikehardy** [comment]
Detecting if HMS is available is a useful feature and quite important for a lot of apps.

You should file an appeal and describe the situation, then point them to here, specifically: 
https://github.com/react-native-device-info/react-native-device-info/blob/370958ee65d408f69eabdf7bf66364b6787023e9/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L546-L553

Checking for availability in that way (the same way we check for GMS, and which Huawei does not complain about) does not violate any policy about loading 3rd party code as we don't use HMS features at all, we simply check for availability.

- If there is a new HMS API that is "more compliant", please let us know and/or post a PR that uses the new API, we'd be grateful and that might get you through because we're no longer using a "non-compliant *version* of Huawei Mobile Services SDK" (note the *version*)
- if you'd like to cut it out completely without any attempt at dialogue with Google or examination if the HMS SDK APIs haved moved, which would contribute to the community and help everyone, go ahead and use https://github.com/ds300/patch-package to just cut that chunk out locally and maintain the patch

If after dialogue with google *and* examination of SDK versions from Huawei it appears that there really is no resolution, then maybe there is something we can do to work around this, but I think HMS *detection* (and GMS detection...) should be allowed

**Comment by mikehardy** [comment]
I listed multiple ways to resolve it. One of which doesn't involve google. How'd it go with patch-package?

**Comment by thanhcuong1990** [comment]
I was try to submit my app to Play store with this patch-package. Seem like It works. 

```diff
diff --git a/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java b/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
index 284e544..d4f2024 100644
--- a/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
+++ b/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
@@ -544,16 +544,7 @@ public class RNDeviceModule extends ReactContextBaseJavaModule {
 
   @ReactMethod(isBlockingSynchronousMethod = true)
   public boolean hasHmsSync() {
-    try {
-      Class<?> huaweiApiAvailability = Class.forName("com.huawei.hms.api.HuaweiApiAvailability");
-      Method getInstanceMethod = huaweiApiAvailability.getMethod("getInstance");
-      Object hmsObject = getInstanceMethod.invoke(null);
-      Method isHuaweiMobileServicesAvailableMethod = hmsObject.getClass().getMethod("isHuaweiMobileServicesAvailable", Context.class);
-      int isHMS = (int) isHuaweiMobileServicesAvailableMethod.invoke(hmsObject, getReactApplicationContext());
-      return isHMS == 0; // ConnectionResult.SUCCESS
-    } catch (Exception e) {
-      return false;
-    }
+    return false;
   }
   @ReactMethod
   public void hasHms(Promise p) { p.resolve(hasHmsSync()); }

```

**Comment by mikehardy** [comment]
Great, that's definitely one way to do it.
It doesn't solve the fundamental problem though, someone needs to invest the time to fix this for real with Google:
- appeal to them and figure out why simply checking availability is a violation?
- see if there is an updated HMS class that we should be using

This library has an incredible number of users, many of which are commercial uses making money I'm sure. Take the time to invest back in your open source dependencies, like this one, and drive it forward. Please work with Google to figure this out

**Comment by hamza-ahmed** [comment]
Hello All , im have same problem for multible apps , whats the solution ?

**Comment by mikehardy** [comment]
@hamza-ahmed you appear to have not read any of the comments, posted a comment yourself anyway. Please read more carefully prior to posting.

**Comment by manikanta1219** [comment]
Hello @mikehardy is there any update regarding this below issue...

We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.

**Comment by mikehardy** [comment]
@manikanta1219 there are no secret updates. 

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

Do the work, make the fix.

**Comment by Xuejiao-Shi** [comment]
hello all, so far huawei has provided analytics, iap, location, map, push, site, nearby, account, ads, adsprime, hms-availability react native plugins new version for this issue. You could obtain the latest plugin from the official website: https://www.npmjs.com/~hmscore

**Comment by mikehardy** [comment]
@Xuejiao-Shi is this something that needs a PR in this module? If so, do you have any plans to submit a PR? I'm not sure what the action is, personally
