### ISSUE TITLE
DeviceInfo.getPhoneNumber() returns null even after adding permissions

### ISSUE THREAD

**Issue by vinitgundeti** [react-native-device-info/react-native-device-info#1425]
## Summary

|             |     |
| ----------- | --- |
| Version     | ^9.0.2   |
| Affected OS | Android   |
| OS Version  | 11  |

## Current behavior

Hi I added permissions
`<uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
<uses-permission android:name="android.permission.READ_SMS" />`

in android/app/src/main 

And I tried to get a number with
`DeviceInfo.getPhoneNumber().then((phoneNumber) => {
	console.log("phoneNumber : ",phoneNumber)
});`

but it returned 'unknown'.
May I know what I am doing wrong? Do I need to add anything else?

In my mobile, sims are added in both slots.

## Expected behavior

It should give me a phone number or choose numbers popup should come

**Comment by sumonsbgc** [comment]
I am also facing this problem.

**Comment by mikehardy** [comment]
The code we use is "correct" but is specifically not guaranteed to work.
The stackoverflow discussion linked in our documentation is informative

In particular this article is interesting: https://android-developers.googleblog.com/2017/10/effective-phone-number-verification.html

We do not currently implement this style (and it won't be perfect either, lots of react-native applications have no access to google play services) but it could work. If you wanted to implement a PR that did this play-services style that could be accessible so long as it was careful to check for availability first, using reflection, so that the module worked correctly on emulators with non play services APIs and/or Huawei devices (which have HMS instead of GMS) etc - similar to our install referrer client

I have no plans to do this myself, confronted with the unreliability of the platform APIs I simply ask the user for a phone number.
