### ISSUE TITLE
Is usage of isBlockingSynchronousMethod problematic?

### ISSUE THREAD

**Issue by bfelbo** [react-native-device-info/react-native-device-info#1435]
This is more of a question than an issue. Please do let me know if I should post it elsewhere instead.

I noticed that this library uses `isBlockingSynchronousMethod = true` [quite a bit](https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java). There's a warning on [RN docs](https://reactnative.dev/docs/native-modules-android#synchronous-methods) saying:

> At the moment, we do not recommend this, since calling methods synchronously can have strong performance penalties and introduce threading-related bugs to your native modules.

Is this not an issue for this library? I'd be very curious to learn more about the tradeoff and why this library uses `isBlockingSynchronousMethod = true`.

This is useful both for understanding whether this library is a good fit for us and to generally understand RN better. Feel free to close this issue and direct me to a better place to post this if there's such a place :)

**Comment by mikehardy** [comment]
You may also notice that there is a parallel method for each of the sync ones that uses a Promise

The issue is that some people need device information prior to the place in code where they may comfortably use asynchronous code (like perhaps to determine what layout to serve). So we offer synchronous methods, with the tradeoffs you describe plus it won't work with javascript debugging either.

But we offer async for most use cases. You could look at the major version releases for v2/v3/v4/v5 I think to see that history.

Use what you need to, make the tradeoffs you need. You may be able to do top-level await now, making the sync stuff no longer really needed
