### ISSUE TITLE
react-native-device-info is incompatible with expo-firebase-analytics and expo-notifications

### ISSUE THREAD

**Issue by ryan-barker-zefr** [react-native-device-info/react-native-device-info#1452]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.0.2   |
| Affected OS | All   |
| OS Version  | All   |

## Current behavior

When trying to use react-native-device-info with expo-firebase-analytics 7.1.1 and expo-notifications 0.16.1, it is not possible to configure them per installation instructions.  If you do not put `firebaseIidVersion`, or the undocumented `firebaseBomVersion`, then `getBundleId` fails. If you put just `firebaseIidVersion` then expo-notifications fails the build due to duplicate classes. If you put just firebaseBomVersion then it fails to find a firebaseIid.

From expo-firebase-analytics
```
  // We can't use BOM, cause it doesn't work with prebuilding and new autolinking.
  // > Could not find com.google.firebase:firebase-core:.
  // Required by:
  // project :expo > host.exp.exponent:expo-firebase-analytics:X.X.X
  // project :expo > host.exp.exponent:expo-firebase-core:X.X.X
  // api platform("com.google.firebase:firebase-bom:24.1.0")
  api 'com.google.firebase:firebase-core:20.1.2'
  api 'com.google.firebase:firebase-common:20.1.0'
  api 'com.google.firebase:firebase-analytics:20.1.2'
```

from expo-notifications
```
  api 'com.google.firebase:firebase-messaging:22.0.0'
```

## Expected behavior

Some configuration should work.
firebaseBomVersion should be documented in readme

**Comment by mikehardy** [comment]
This is an "in-between" issue, that is, it is in between the two repositories. I'm loathe to take responsibility for it here because wouldn't you know it, I maintain react-native-firebase and I know this line:

>   // We can't use BOM, cause it doesn't work with prebuilding and new autolinking.

...is basically saying "we can't do the sensible thing that firebase recomends to manage versions because of Expo's build system constraints, so we're going to do something really difficult"

Then the result is that you the expo firebase consumer have something really difficult to deal with. That's just the way it goes when you don't use the BoM unfortunately and go for independent versions instead. We moved away from them because they were just so messy (https://invertase.io/blog/react-native-firebase-versioning)

That said, your path forward, if you can't use the BoM is:
- determine what BoM the Expo firebase stuff *would* correspond to (use this: https://firebase.google.com/support/release-notes/android - looks like it maps to this one https://firebase.google.com/support/release-notes/android#bom_v29-3-0 but double check me)
- use that version of the IID (21.1.0 it looks like? Did you try that?)

You're right on this part:

> firebaseBomVersion should be documented in readme

Looks like ti was missed in #1133 - a PR to turn your "should" into "done!" would be awesome, the github web PR flow is great for little docs edits like that

**Comment by mikehardy** [comment]
I appreciate the understanding, and for my part I appreciate a) big dependency messes and incremental change and b) that expo in general provides a ton of value while boostrapping at minimum, and beyond. There are no easy decisions there

I'm surprised the BoM that matches is 24.1.0 though! Wow, that's quite old

I'm actually a huge fan of patch-package. It does seem a little eww but then at the same time, combo of open source and patch-package, it's magic. You were not stuck for too long and there's no way an urgent un-stick like that is possible in more closed ecosystems.

Glad you got it worked out, at least for now
