### ISSUE TITLE
Support for foldable devices

### ISSUE THREAD

**Issue by nschild** [react-native-device-info/react-native-device-info#1455]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.0.1|
| Affected OS | Android |
| OS Version  | 12 |

## Current behavior
In the android emulator, I am logging 3 values to the console to see if RNDI is able to see when a device is folded.
    `console.log('breakpoint', DeviceInfo.isTablet(), await DeviceInfo.isTabletMode(), DeviceInfo.getDeviceType())`

If the app was opened in tablet mode, it will always say `LOG  breakpoint true false Tablet` until it is hard closed or I press "r" in the metro bundler.
The same is for if opened in mobile mode, `LOG  breakpoint false false Handset`

Note1: DeviceInfo.isTabletMode() always says false

Note2: RN reloads the ui when the breakpoint changes, but that is an issue for another ticket somewhere else.

## Expected behavior 
  DeviceInfo.isTablet(), await DeviceInfo.isTabletMode(), DeviceInfo.getDeviceType()) return the correct values.

It would be nice if there was a hook for these, I suppose it could tie into useWindowDimensions().

**Comment by mikehardy** [comment]
I think this is another case of "things that used to be constant are no longer constant", ironically the reverse of [the breaking change in v5.0.0](https://github.com/react-native-device-info/react-native-device-info/blob/master/CHANGELOG.md#500)

https://github.com/react-native-device-info/react-native-device-info/blob/7387a623a4f9a4445b81a73172fb54a9c5ef5f37/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L198

That's a constant, I think it either needs to be made non-constant or - it appears from an [unrelated PR](https://github.com/invertase/react-native-firebase/pull/6529/files/8ea07fb5a1bfa8ac7b3733bea83b040c3513f51d#diff-945d05be567b9871eff943790a8b6ff7efde8bcd48a0b41d24d240b4687859c0R246) that if you change a constant value it may actually not be cached and thus show up correctly in the future

If it needs to be made non-constant then it's a breaking change and you just take it out of constants, and refer to the implementation dynamically in the sync/async methods

But if my recent experience on react-native-firebase appears correct, I think this change could be handled without a breaking change and you would make a new receiver, register the receiver in the AndroidManifest.xml for uiChange events related to size, re-resolve the device type and stuff that in to constants. Or maybe - in a less-intrusive way since adding configuration change to the AndroidManifest might affect consuming apps, just do a listener instead like so: https://developer.android.com/guide/topics/large-screens/make-apps-fold-aware#java_callbacks - that is probably the best solution.

Personally? I wouldn't rely on this and I use the useWindowDimensions hook because it's easy and it works but if you need this functionality I could see a PR here for java callbacks implemention updating constants and a quick video showing how on the android foldable emulator (or a real device?) the value changed if you hit a button on the example app.js forcing contants to re-render or similar to demo

**Comment by schie** [comment]
I started looking into this.

After looking into the different [DisplayFeatures](https://developer.android.com/reference/kotlin/androidx/window/layout/WindowLayoutInfo#displayFeatures()) the device could be in and how to infer things, here's what I found:

The definition of `isTablet` goes out-the-window IMO if you can have in-between states — I think. With the 'half'-open state possibly implying different behaviors, then potentially opening different ways depending on the device and such, my smooth-brained-self gave up.

I think this is so based on the context of the device / situation, that the best we could do is just add a hook that provides those display features, and let the app developer decide that those values mean to them.

This is a tough one for sure

**Comment by cgibson-emesent** [comment]
Can we please reopen and remove this from the constants? In React Native I'm using the below and `react-native-device-info` is failing to update the isTablet status. I would expect `DeviceInfo.isTablet()` to always run when I call `DeviceInfo.isTablet()`, especially now that foldable devices have been around for a while and are becoming more mainstream. 

```
Dimensions.addEventListener("change", () => {
      console.log("DeviceInfo.isTablet()", DeviceInfo.isTablet()); // Always returns what was cached the first time it ran.
});
 ```
