### ISSUE TITLE
getUniqueId returning null on a small number of Android devices (version 6.2.1)

### ISSUE THREAD

**Issue by owenbirdsall** [react-native-device-info/react-native-device-info#1477]
I have inherited a legacy and fragile codebase that relies heavily on getUniqueId to manage user accounts. Recently I have noticed that getUniqueId is returning null on some Android devices (ie Samsung Galaxy Note 10 running Android 11). Would updating the library to the latest version likely fix this issue? ...also if I were to do that, would the uniqueId's be the same as they were in version 6.2.1 or are they now generated in a different way?

Version: 6.2.1
Affected OS: Android
OS Version: 10/11

**Comment by mikehardy** [comment]
Did you read the note on getUniqueId? https://github.com/react-native-device-info/react-native-device-info#getuniqueid

strange getUniqueId is returning null, I wouldn't expect that as it is using ANDROID_ID under the covers, and that is not documented as being able to return null https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

That said on Android you might like the new implementation of getInstanceId that I just merged. It will return a stable UUIDv4-type value on Android that should survive for lifetime of an app installation #1475

The heart of that implementation is the idea " see if there is already a UUIDv4 instance ID in shared preferences, if not let's just generate a UUIDv4 string, store it in shared preferences. Return that instance ID"

Nothing else will likely fix the issue, if ANDROID_ID is returning null for whatever reason, there is not much you can do.

**Comment by owenbirdsall** [comment]
Thanks Mike!

So I assume as it was using ANDROID_ID in 6.2.1 and is still using ANDROID_ID that updating to the latest library wouldn't cause me any issues given that the ID being returned won't change between versions.

I will double check to verify that it is definitely returning null, perhaps there is a setting on Android that allows users to block apps from accessing the device id? ...it's interesting because we know that the device this started happening on had previously returned a valid ID. The problem began happening - possibly after they updated the OS or maybe changed a setting. Unfortunately I don't have access to the device.

Thanks for the tip on getInstanceId, maybe something I can look to switch things over to in the future, but like I said it's a fragile project so I need to have a light touch with any changes.

**Comment by mikehardy** [comment]
If 6.2.1 was using ANDROID_ID (use git history to verify...) the current is, so that should be stable, at least, as implementation

I linked the ANDROID_ID documentation, you may examine it to see how it is supposed to behave (assuming vendors don't mess with the implementation - check stackoverflow for that, to your point on some maybe setting to let users maybe block...)

If your app is very keen on getUniqueId, you might put a wrapper over it so you have more control, and switch to getInstanceId *if* getUniqueId returns null, as that doesn't rely on any vendor APIs or hardware identifiers or fancy code at all - you can see from the PR how trivial the shared preferences + UUID code is, and that's a benefit IMHO, that ID should (finally!) be stable and easily understood
