### ISSUE TITLE
hasNotch and hasDynamicIsland return false for iPhone 14 Pro

### ISSUE THREAD

**Issue by exoslav** [react-native-device-info/react-native-device-info#1527]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.5.1 |
| Affected OS | iOS |
| OS Version  | 16.2 |

## Current behavior
`hasNotch` and `hasDynamicIsland` returns `false` for iPhone 14 Pro.

Even though, that `iPhone 14 Pro` is listed in `devicesWithNotch.js` and `devicesWithDynamicIsland.js`, both `DeviceInfo.hasNotch()` and `DeviceInfo.hasDynamicIsland()` returns `false`.

I am running the app in the emulator.
```
// node_modules/react-native-device-info/lib/commonjs/index.js

function hasNotch() {
  if (notch === undefined) {
    let _brand = getBrand();

    let _model = getModel();

    console.log('_brand:', _brand) // "Apple"
    console.log('_model:', _model) // "iPhone"

    notch = _devicesWithNotch.default.findIndex(item => item.brand.toLowerCase() === _brand.toLowerCase() && item.model.toLowerCase() === _model.toLowerCase()) !== -1;
  }

  return notch;
}
```

## Expected behavior
`DeviceInfo.hasNotch()` and `DeviceInfo.hasDynamicIsland()` returns `true` for `iPhone 14 Pro`.

**Comment by mikehardy** [comment]
PRs happily accepted, merged + released if you can reproduce it and fix it. Could just be that the model number isn't matching

**Comment by chuanmin13** [comment]
Have the same issue with `DeviceInfo.hasNotch()` return false for iPhone14 as well.

I've found out that the model value is come from `NativeModules` in React-Native.

After console.log the `NativeModules.RNDeviceInfo` for diffirent Xcode Simulator, found that all the iPhone 14 devices are unabled to get the proper model name.

Please refer below: (I'd deleted some logs for better understanding)
```
// iphone 14
{
  ...,
  "brand": "Apple",
   "deviceId": "iPhone14,7",
  "deviceType": "Handset",
  "isTablet": false,
  "model": "iPhone",
  "systemName": "iOS",
  "systemVersion": "16.4"
}

// iphone 14 Pro Max
{
  ...,
  "brand": "Apple",
  "deviceId": "iPhone15,3",
  "deviceType": "Handset",
  "isTablet": false,
  "model": "iPhone",
  "systemName": "iOS",
  "systemVersion": "16.4"
}


// iphone 13 Pro Max
{
  ...,
  "brand": "Apple", 
  "deviceId": "iPhone14,3",
  "deviceType": "Handset", 
  "isTablet": false,
  "model": "iPhone 13 Pro Max", 
  "systemName": "iOS",
  "systemVersion": "16.4",
}
```

We only get 'iPhone' as the model name, and that end up find no matching in `devicesWithNotch` list in here src/internal/devicesWithNotch.ts, turns out return false for `DeviceInfo.hasNotch()`


The NativeModules in React-Native seems to be written in ObjectiveC/Swift/Java and I have no idea with that :(
Appreciate that if anyone could help with this!! Thanks!!

**Comment by forbesgillikin** [comment]
I experienced this issue as well after upgrading from 8.1.2.

Just needed to install the latest pods 😄 

`hasNotch()` and `hasDynamicIsland()` work fine on iPhone 14 Pro
