### ISSUE TITLE
DeviceInfo.getSerialNumber() return 'unknown'

### ISSUE THREAD

**Issue by DevHisham** [react-native-device-info/react-native-device-info#1563]
I am trying to get serial number for android & ios but always return **unknown**

**Comment by mikehardy** [comment]
Please read documentation prior to opening issues

https://github.com/react-native-device-info/react-native-device-info#getserialnumber

> Gets the device serial number. Will be 'unknown' in almost all cases [unless you have a privileged app and you know what you're doing](https://developer.android.com/reference/android/os/Build.html#getSerial()).

I will assume since you have not specified that you have a privileged app and that you know what you are doing, that you do not have a privileged app and/or [do not know what you are doing](https://developer.android.com/reference/android/os/Build#getSerial()) because you are not using the recommended resettable identifiers that protect user privacy

If I'm wrong we can reopen
