### ISSUE TITLE
iPhone 15 hasNotch and hasDynamicIsland

### ISSUE THREAD

**Issue by maxperry** [react-native-device-info/react-native-device-info#1566]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.9.0   |
| Affected OS | iOS   |
| OS Version  | 17  |

## Current behavior

Both `hasNotch()` and `hasDynamicIsland()` are false on iPhone 15 & 15 Pro simulators.

## Expected behavior

Both `hasNotch()` and `hasDynamicIsland()` should return true.

**Comment by MensurRasic** [comment]
Works on 10.10.0 but doesn't work on the latest, 10.12.0 version...

**Comment by mikehardy** [comment]
@MensurRasic that's pretty odd given that nothing changed in that area - you can check the diffs yourself https://github.com/react-native-device-info/react-native-device-info/compare/v10.10.0...v10.12.0

Suspect strange local project or device behavior, not this repo

**Comment by MensurRasic** [comment]
Well initially I was on `10.7.0` and `hasNotch()` was not working on `iPhone 15 Pro Max simluator`.
I upgraded to `10.12.0` and `hasNotch()` was still not working.
I downgraded to `10.10.0` and it's working properly.

Meanwhile, I haven't changed anything on my project, you can probably give it a shot and see in practice.

Also, I am not sure if `hasNotch()` should be returning `True` on `iPhone 15 Pro Max` if `Apple` removed it... `hasNotch()` should return false and `hasDynamicIsland()` should return true.

**Comment by mikehardy** [comment]
I see what you are saying.
However a diff is a diff, code is code. There are no changes in that area

The whole thing about notches and dynamic islands etc is inferior to a general solution like https://github.com/th3rdwave/react-native-safe-area-context/ regardless - those methods existed here since before react-native-safe-area-context existed, but now that it exists everyone should use that and these methods should really be deprecated

**Comment by lennertderyck** [comment]
> I see what you are saying. However a diff is a diff, code is code. There are no changes in that area
> 
> The whole thing about notches and dynamic islands etc is inferior to a general solution like https://github.com/th3rdwave/react-native-safe-area-context/ regardless - those methods existed here since before react-native-safe-area-context existed, but now that it exists everyone should use that and these methods should really be deprecated

I don't think that's the point. 

In my case I need to offset something when there is a notch or something similar. So there are certainly other people as well that need this solution.

**Comment by mikehardy** [comment]
I don't believe you grasped the full implication of something like react-native-safe-area-context.

It doesn't just answer the question "do I need to offset", which these APIs do. It answers the question how much, where etc. It is a full general purpose solution vs the very low-information-content hack that is the APIs here.

Regardless: the *most* important statement from a code point of view is that *there were no changes to the code in that area between the versions you specify*. Isn't it weird that behavior changes despite no code changes? That should be a focus of investigation I think - because I've never seen unexplained behavior changes in code that didn't change where the final / root cause explanation wasn't worth knowing
