### ISSUE TITLE
README documentation inconsistency around `getPowerState` and `usePowerState` / `RNDeviceInfo_powerStateDidChange`

### ISSUE THREAD

**Issue by simon-assistiq** [react-native-device-info/react-native-device-info#1587]
In the README `getPowerState()` returns an object with `batteryState`, `batteryLevel` and `lowPowerMode`.

But for `usePowerState` or `RNDeviceInfo_powerStateDidChange` it only returns whether the device is plugged in or not, which is called "batteryState" in `getPowerState`. And there is no listener listed called `useBatteryState` (and for that matter there isn't one for low power mode).

Is there a reason for this apparent inconsistency?

I suppose renaming at this point would be an annoying breaking change though.

**Comment by mikehardy** [comment]
Inconsistent perhaps, but naming is hard (no one wants to code or help troubleshoot but everyone wants to suggest a name... see "bikeshedding" https://en.wiktionary.org/wiki/bikeshedding) naming is usually not the actual important thing over time as long as the docs explain exactly what everything does. Which they do I think.

There is useBatteryLevel which seems fine.

Is there a reason? Not really 🤷  people that propose PRs usually get to name things and if they seem reasonable at all I'm inclined to merge them because thank god sometimes people actually propose PRs and move open source stuff forward. I try not to get bogged down too much in PR review back and forth

**Comment by simon-assistiq** [comment]
Seems actually `usePowerState` does in fact return the full object, but `RNDeviceInfo_powerStateDidChange` just returns the battery state (charging/not charging)

The comment `// 'charging'` next to the `usePowerState` code sample in the README implies otherwise.

**Comment by mikehardy** [comment]
Ah! If that's the case a PR to the README to indicate what it's actually doing would be fantastic

**Comment by simon-assistiq** [comment]
Worth noting my project is still on only 8.7.1 but I skimmed through the releases and didn't see anything obvious that would have affected this. Still, would need to test the latest release first.

**Comment by simon-assistiq** [comment]
ok, seems like both give the power state object with the three properties on the latest version.
README adjustment still worthwhile, but at least it's relatively simple.
