### ISSUE TITLE
RNDeviceInfo is adding `AD_ID` permission through `play-services-iid` ?

### ISSUE THREAD

**Issue by dprevost-LMI** [react-native-device-info/react-native-device-info#1671]
## Summary

|             |     |
| ----------- | --- |
| Version     |  10.14.0   |
| Affected OS | Android   |
| OS Version  | 14 |

## Current behavior
Hi, we upgraded to SDK 34 and then uploaded a build manually to the Google Store. We got a consent form request for using `com.google.android.gms.permission.AD_ID` permission.

After using `./gradlew app:dependencies > dependencies.txt` and looking at `manifest-merger-blame-gotoconnect-debug-report.txt`, I was able to find the lib `play-services-iid-17.0.0` pulling this permission `AD_ID`. It comes from `react-native-device-info` pulling it from the [build.gradle](https://github.com/react-native-device-info/react-native-device-info/blob/34a80b6e1516f04f251a50273c41b1f3fb39e1f7/android/build.gradle#L67-L70)

I commented the deps to be sure and then ended up seeing `firebase-messaging-23.2.1` pulling the same permission, but that is for another repository 😉 

## Expected behavior

`react-native-device-info` should not add the `com.google.android.gms.permission.AD_ID` permission even through it's dependencies.

## More Comments

From the `build.grade`, I can see that we either pull the Google Play service or the Firebase one. I'm not sure where and how I can configure that to try to stop pulling `implementation "com.google.android.gms:play-services-iid:$iidVersion"` and fix my issue

## Logs
relevant content of `/manifest-merger-blame-gotoconnect-debug-report.txt`
```
109-->[com.google.android.gms:play-services-iid:17.0.0] [obfucated]/.gradle/caches/transforms-3/eabf05445f53c5e97813df2a1d4cf2cb/transformed/jetified-play-services-iid-17.0.0/AndroidManifest.xml:23:5-82
109-->[com.google.android.gms:play-services-iid:17.0.0] [obfucated].gradle/caches/transforms-3/eabf05445f53c5e97813df2a1d4cf2cb/transformed/jetified-play-services-iid-17.0.0/AndroidManifest.xml:23:22-79
110    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
```

gradle relevant dependency tree `./gradlew app:dependencies > dependencies.txt`:

```
+--- project :react-native-device-info
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.73.9 (*)
|    +--- com.android.installreferrer:installreferrer:1.1.2 -> 2.2
|    \--- com.google.android.gms:play-services-iid:17.0.0
|         +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
|         +--- androidx.core:core:1.0.0 -> 1.9.0 (*)
|         +--- com.google.android.gms:play-services-base:17.0.0 -> 18.0.1 (*)
|         +--- com.google.android.gms:play-services-basement:17.0.0 -> 18.2.0 (*)
|         +--- com.google.android.gms:play-services-stats:17.0.0 -> 17.0.2 (*)
|         \--- com.google.android.gms:play-services-tasks:17.0.0 -> 18.0.2 (*)
```

**Comment by mikehardy** [comment]
🤔  agreed we should not be adding that
I'm traveling right now so I don't have time to investigate how to change this functionality or make it optional but that should be the future course

I *believe* you can add the android xmlns:tools namespace to your AndroidManifest.xml if you have not already, and then you can make an XML entry with tools:remove for AD_ID to force it out - there will be answers all over the internet with those search terms I believe, so you can have a workaround

**Comment by mikehardy** [comment]
Obligatory mention: PRs more than welcome with any reasonable solution for this, and they can be merged almost immediately if they are backwards-compatible

**Comment by mrpmohiburrahman** [comment]
Hi, @mikehardy , 
I want to work on this.
I'll open a pr in couple of hours.

**Comment by mrpmohiburrahman** [comment]
Hi, @mikehardy , 
please, check this PR: https://github.com/react-native-device-info/react-native-device-info/pull/1673

**Comment by dprevost-LMI** [comment]
I'm surprised we can simply remove it. Was there any purpose for using `com.google.android.gms:play-services-iid` ?

**Comment by mikehardy** [comment]
@dprevost-LMI there was a purpose, it was a default implementation for getDeviceId - the PR was altered so this implementation still exists but now has to be manually enabled instead of just always being there

**Comment by dprevost-LMI** [comment]
> I believe you can add the android xmlns:tools namespace to your AndroidManifest.xml if you have not already, and then you can make an XML entry with tools:remove for AD_ID to force it out - there will be answers all over the internet with those search terms I believe, so you can have a workaround

Thanks! Yeah we are trying it out, and by log inspection it is working but we still have trouble with automatic upload through fastlane vs manual. Anyway, this is way out of your scope now!

Thanks guys for this fast fix!

**Comment by mikehardy** [comment]
@mrpmohiburrahman for the win, right! PRs make the open source world go around :-)

**Comment by mrpmohiburrahman** [comment]
> @mrpmohiburrahman for the win, right! PRs make the open source world go around :-)

Glad I could help! 😊
Thanks for the kind words! 🚀

**Comment by mwmcode** [comment]
Hi @mikehardy 
Does this mean, we need to declare AD_ID in PlayStore if we are using `getDeviceId` ?

>Currently getting `Issue found: Invalid Data safety form` when publishing my app on PlayStore, even though all AD permissions are removed.

**Comment by mikehardy** [comment]
@mwmcode is there something missing or that could be clearer in the release note from the CHANGELOG?

> fix(android)!: remove AD_ID permission requirement by removing auto-addition of play-services-iid
> 
> BREAKING CHANGE: removed default fallback getDeviceId via play-services-iid dependency
> 
> This dependency has the unfortunate side effect of including AD_ID permission, which is
not permissible for many types of applications.
> 
> If you relied on this functionality, you will need to define googlePlayServicesIidVersion in your
android gradle build files ext version block. We previously used version 17.0.0 but there may be
newer versions you could use if they work for

If you rely on the device ID from google's play-services-iid dependency, you now need to add that dependency manually in the current version of react-native-device-info (as mentioned in the CHANGELOG note above) and the implication is that if you do that then yes you will have AD_ID in your app and you'll need to declare it and get permission for it (as mentioned in the CHANGELOG note above)

I can't directly answer your question because I don't know if you really rely on the getDeviceId implementation that uses play-services-iid, and I don't know if it's permissible for your app, etc etc.

**Comment by mwmcode** [comment]
@mikehardy thank you for the detailed response.

The [CHANGELOG for v14](https://github.com/react-native-device-info/react-native-device-info/releases/tag/v14.0.0) mentions `getInstanceId` not `getDeviceId` which maybe why I skipped it, since I'm not using `getInstanceId`. I can see now that your [comment on the PR](https://github.com/react-native-device-info/react-native-device-info/pull/1673#issuecomment-2439167521) does mention it.

The codebase I have calls `getDeviceId` which started getting rejected by play store. (after upgrading). _I think I can remove the call (rather than adding AD_ID permission) since it was added for debugging purposes only_.

Is my understanding correct that "moving on, AD_ID will need to be defined and declared in Play Store if you want to use `getDeviceId`"? If so, should the [`getDeviceId` docs](https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getdeviceid) be updated to reflect this?

**Comment by mikehardy** [comment]
@mwmcode  I encourage you to inform yourself of exactly what is going on by examining the source:

https://github.com/react-native-device-info/react-native-device-info/blob/fee1db459cccb98428b8e28f37f506a71d2291ff/android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceIdResolver.java#L25-L53

Under the covers it is called "instance id" since it used to be based on that old google play services instance id code, before adding the capability of using the newer-style firebase style, before adding the capability of just being a randomly generated UUIDv4 ID.

If you read the code you'll note that first it'll return any ID that was saved from previous run, then it will *try* to load the instance ID library and use it, then it will *try* to load the firebase library and use it, and if neither of those are found it'll just do a UUIDv4 (which is what most people want, since it doesn't require AD_ID permission).

So it depends on what libraries you have linked in to your app. That's how it works. You will need to think about that, and you will need to act according to your understanding and your project's needs

**Comment by mwmcode** [comment]
I get it now. Thank you!
