### ISSUE TITLE
isTablet resolving to false on Android tablet

### ISSUE THREAD

**Issue by arapocket** [react-native-device-info/react-native-device-info#1678]
## Summary

|             |     |
| ----------- | --- |
| Version     | 14.0.0   |
| Affected OS | Android  |
| OS Version  | 35  |

## Current behavior

`isTablet()` resolves to false on a Pixel tablet simulator when the app is in letterboxed view.

## Expected behavior

`isTablet()` should resolve to true regardless if the app is in letterbox view or not

**Comment by mikehardy** [comment]
Hi there - PRs happily accepted if you post something that appears to fix it without regressing previous behavior (and potentially breaking layout algorithms people are relying on). Not sure that's possible but if there's a PR that can do it, I can merge it.

**Comment by arapocket** [comment]
Setting resizeableActivity to false in your AndroidManifest seems to fix this

**Comment by mikehardy** [comment]
Just as a preference, I think isTablet is not terribly useful. If it is used to select between different layouts (single-column, double-column etc) it's better to take the actual content width and then set breakpoints for different values, like "small, medium, large" etc and make layout decisions based on the actual width. Put that in a hook so layout is reactive, and you have a responsive UI. Other than that, I'm not sure what isTablet is really useful for, and for layout decisions, it's not sufficient. So I don't personally use it FWIW, just maintain it forever since it existed before

**Comment by arapocket** [comment]
> Just as a preference, I think isTablet is not terribly useful. If it is used to select between different layouts (single-column, double-column etc) it's better to take the actual content width and then set breakpoints for different values, like "small, medium, large" etc and make layout decisions based on the actual width. Put that in a hook so layout is reactive, and you have a responsive UI. Other than that, I'm not sure what isTablet is really useful for, and for layout decisions, it's not sufficient. So I don't personally use it FWIW, just maintain it forever since it existed before

Hah thanks for the insight. I feel your pain. 

I'm using it for 2 cases:

- analytics on users (tracking tablet vs mobile users)
- locking orientation based on the device type (unlock for tablets, lock to portrait for phones)

But I can certainly just check the screen width for either of those cases. Thanks.
