### ISSUE TITLE
getTotalDiskCapacity() do not get the same value as ”System Setting“ In android

### ISSUE THREAD

**Issue by jcliang1212** [react-native-device-info/react-native-device-info#346]
In Android, getTotalDiskCapacity() do not get the right value。 So I change the Java code as follow:
```java
public Long getTotalDiskCapacity() {
    try {
      StatFs root = new StatFs(Environment.getRootDirectory().getAbsolutePath());
      return root.getBlockCountLong() * root.getBlockSizeLong();
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }
``` 

But the function returns 4.3GB, but the System Setting show 8.0GB. The Android device is "SM-T719C - 6.0.1". Can anyone tell me why? Thanks! @crafterm @doochik @DracoBlue @stevemoser @jeveloper

**Comment by machour** [comment]
Should be fixed by #597

**Comment by mikehardy** [comment]
@machour this one is actually not fixed - I fixed integer overflow with a very focused change, and this one will need a separate change to use different native APIs in a thoughtful way. I didn't attempt it in the integer overflow fix

**Comment by mikehardy** [comment]
If someone wants to submit a PR, that would be great. A good example of the task is in this stack overflow thread: https://stackoverflow.com/a/30401010

Basically, you have to get *all* the external storage directories and get all of their sizes. You should probably also get the internal storage, take care to de-duplicate all of them and that will be your total capacity (and total free space if you call that native API) as well

**Comment by goislimat** [comment]
_I know this issue is opened for a while but I have a possible solution to present._

I'm working on an app that does a check on the total disk capacity. This function works fine for iOS, but on Android, I'm getting values that doesn't seem right.

This function is currently implemented as follows:

```java
  @ReactMethod
  public BigInteger getTotalDiskCapacity() {
    try {
      StatFs root = new StatFs(Environment.getRootDirectory().getAbsolutePath());
      return BigInteger.valueOf(root.getBlockCount()).multiply(BigInteger.valueOf(root.getBlockSize()));
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }
```

When I execute the `getTotalDiskCapacity()` function on my Android (**Xiaomi Mi A2 Lite with 32 GB of disk**) I get 2,600,857,600 bytes (~ 2,6 GB) as result.

Then reading the docs for [Android Environment](https://developer.android.com/reference/android/os/Environment.html) and [StatFs](https://developer.android.com/reference/android/os/StatFs) I tried using the `getDataDirectory()` instead of `getRootDirectory()` as follows:

```java
  @ReactMethod
  public BigInteger getTotalDiskCapacity() {
    try {
      StatFs dataDir = new StatFs(Environment.getRootDirectory().getAbsolutePath());
      return BigInteger.valueOf(dataDir.getBlockCount()).multiply(BigInteger.valueOf(dataDir.getBlockSize()));
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }
```

With this change I started getting 22,860,075,008 bytes (~22,8 GB) as result. This value is the same as displayed in the Windows Explorer when I connect my device for file transfer.

Then I downloaded some apps that scan disks like [EasyDisk](https://play.google.com/store/apps/details?id=com.bluepea.daisydisk) and [Disk Usage](https://play.google.com/store/apps/details?id=com.mobile_infographics_tools.mydrive). Checking the values that I got with the values returned from these two apps and the value displayed on Windows Explorer, I came with the solution:

```java
  @ReactMethod
  public BigInteger getTotalDiskCapacity() {
    try {
      StatFs rootDir = new StatFs(Environment.getRootDirectory().getAbsolutePath());
      StatFs dataDir = new StatFs(Environment.getDataDirectory().getAbsolutePath());

      BigInteger rootDirCapacity = BigInteger.valueOf(rootDir.getBlockCount())
          .multiply(BigInteger.valueOf(rootDir.getBlockSize()));
      BigInteger dataDirCapacity = BigInteger.valueOf(dataDir.getBlockCount())
          .multiply(BigInteger.valueOf(dataDir.getBlockSize()));

      return rootDirCapacity.add(dataDirCapacity);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }
```

Which returns me 25,460,932,608 bytes (~ 25,4 GB). This is the same value presented on Disk Usage app and one that looks more correct to me.

I tried running this edited function on some other devices and I got more reliable results.

**Comment by mikehardy** [comment]
Interesting! This is great information and may serve as the core of the future implementation here.

I wonder actually if it wouldn't be better to present a "grand total" sum like the implementation you've settled on but also expose the underlying APIs to get finer-grained space available for those that want it - I usually lean towards a simple aggregate API but also exposing the details for those that need it since there's no other way to access device info via javascript otherwise. 

Either way, the implementation you shared would be very useful - thank you

**Comment by mikehardy** [comment]
So then if there were a PR which exposed a total like above, and a second one that maybe exposed an array of "API type" vs "total size"/"space available" information I'd probably merge it immediately, since we wouldn't have to take a philosophical position per se, and app developers could either go easy (grand total) or detailed as their use case called for but we wouldn't have made any decisions for them, limiting them in anyway

**Comment by Holymith** [comment]
Any news on this? Already tried @goislimat solution and it gives the same result as getTotalDiskCapacity(), not the same value as in system settings

**Comment by mikehardy** [comment]
These were reworked in #1054 (and some follow-ons), I think it should be working now. Are you up to date on versions in this module @Holymith ?

**Comment by Holymith** [comment]
@mikehardy yes, i am using
"react-native-device-info": "^7.0.2"
"react-native": "0.63.1"
I get 14 GB from a moto g5 play 16GB from
DeviceInfo.getTotalDiskCapacity().then(a => console.log(a));

**Comment by mikehardy** [comment]
Hmm - I wonder it that is just a discrepancy (as mentioned above) between root and data vs data only or similar. The best I can recommend is reaching right into node_modules to edit the java and add some System.err.println()'s so you can inspect the values and compare. Once we have an idea what exactly is going on we can perhaps fix it. Maybe the answer is (as hinted at above) a data-only capacity API or similar
