### ISSUE TITLE
getUniqueId is not unique is some cases in iOS

### ISSUE THREAD

**Issue by ou2s** [react-native-device-info/react-native-device-info#519]
Hello,

Some of our users experienced an issue with the ID that we retrieved via `getUniqueId()`: they have  the same ID across two different devices.

We found a way to reproduce the problem: if a user uses the same Apple ID across two devices and has used iCloud to restore a backup from one device to another, `getUniqueId` return the same string.

We are thinking about forking the library and removing the mechanism that saves and read from UserDefaults and Keychain. But before that, may I ask why this mechanism was implemented? Why not retrieve the ID always with the same mechanism using `[[UIDevice currentDevice].identifierForVendor UUIDString];` ?

PS: thanks for the lib, used it on several projects!

**Comment by machour** [comment]
Hi Oussema :)

Not sure on why the mechanism was implemented, maybe it was meant to make sure the Uid stays the same (https://stackoverflow.com/questions/31344173/uidevice-currentdevice-identifierforvendor-can-this-change-on-an-ipad#answer-31344503)

Feel free to fork this project and adapt it to your needs, or better yet, submit a PR to solve this.

**Comment by tsemerad** [comment]
I'm running into this same issue. I have a customer who is installing my app on one device, then cloning the device to multiple iPads.

Usually I want the id to be saved in the Keychain, because my use case really values knowing the number of devices that have launched the app, not the number of installations. But in this case I need to override that.

@ou2s and @machour, what do you think of adding an optional parameter to cache the id?

Have it still do the caching by default, but have the option to pass in `false` or `{ cache: false }`?

We'd have to update the docs to explain that `cache: false` only works on iOS, since `ANDROID_ID` appears to not need caching, as described [here](https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html):
>The ANDROID_ID value won't change on package uninstall/reinstall, as long as the package name and signing key are the same. Apps can rely on this value to maintain state across reinstalls.

**Comment by hxqbeyond** [comment]
Me too

**Comment by mikehardy** [comment]
#538  should have an implementation more like #60 and thus not run into this. If you forked and implemented something like #60 or proposed a PR that did that, it could get us going in that direction

That proposed implementation would not survive app uninstall/reinstalls but I think an app that wants to do that might be better served with firebase or similar?
