### ISSUE TITLE
Please make isEmulator and getDeviceName into constants

### ISSUE THREAD

**Issue by robertherber** [react-native-device-info/react-native-device-info#879]
# Feature Request

Please make isEmulator and getDeviceName into constants again.

## Why it is needed

I'm using isEmulator and getDeviceName when bootstrapping reactotron, which is in turn tangled up with Redux bootstrapping. Having this async makes things veeery complicated.. :)

**Comment by mikehardy** [comment]
First let me say I feel the pain, and obviously am trying to find a balance

However - getDeviceName is not a constant in real life, so that one likely not.

isEmulator is potentially expensive even if static, which is why it is not static right now.

Is it possible to use those in your project via the xxSync APIs and *if* the chrome debugger is an issue, detect debugger and mock the results (https://github.com/react-native-community/react-native-device-info/issues/776#issuecomment-535627454)? Possibly best of both worlds and no need to deliberate here - esp re DeviceName which really is dynamic

**Comment by robertherber** [comment]
That's what I'm doing now. Not really optimal though.

Could at least isEmulator be made constant? I see that at least for iOS it's basically using the same logic as `getDeviceId` which is already a constant - so shouldn't be that expensive, right? On Android there are a few string comparisons - is that what you mean by potentially expensive or am I missing something here?

One way to optimize - and I guess that goes for more calls than isEmulator - is to move some of the "constant logic" to JS so it's only executed when needed. Just keep the most basic stuff as native constants (on iOS getDeviceId and on Android the build constants needed) and move the string comparisons to JS so it's only executed when needed. I guess making the string comparisons into regexes could help a bit as well.

I think I understand what you're trying to accomplish with this (adding as little startup overhead as possible in this widely used library?). Just keep in mind that it's easy to overengineer this kind of stuff - which in the end is executed mostly native and will probably have very minor effects on performance compared to other factors. Ease-of-use and DX is obviously very important for these kind of generally used libraries as well - and in this case I'm not sure whether minor performance gains are more important.

Didn't really mean to write this long of a post - but I guess these are my 5 cents! :) Most of all - thanks for your work on this really useful library @mikehardy!

**Comment by mikehardy** [comment]
The thing that worries me about isEmulator is we're not getting a lot of android simulators out there - there is a PR which could add a lot more #713 - but I'm nothing if not pragmatic, and the current isEmulator check could be a constant to my way of thinking. You are absolutely correct it is not doing a whole lot currently.

Perhaps if I merge something like #713 (which is stale at the moment anyway) It becomes an optional async "deeper" isEmulatorComplete or something.

If you make a patch for isEmulator that follow the lines of the recent PRs re-constant-ifying (made up word) a couple things I'd merge it. It'll be another breaking change because of the promise semantics but I'm not getting much push back on these tiny changes for constants so I feel it can go out without a revolt
